# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eae1209bc331687dcc23f6ef560465b44ada5d29b5c9a7801c96a5fc7ff5c91accf0bd06290581ec0d28245d1ea7fd9a5ee8d0435a032fe860766eb432cffdbb

test:
  secret_key_base: 9016d4cc482bd4b4c50fceeca3f8961e4c385a43e714bd12b8efd107fe0eec77a40791b37acbb7625df25fcecbcf264228b01cae39818f4cc4a1af3796316f4f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
